const CLOUDINARY_SECRETS = {
    UPLOAD_PRESET: "YOUR_CLOUDINARY_PRESET",
    CLOUD_NAME: "YOUR_CLOUD_NAME",
    CLOUD_API_SECRET: "YOUR_CLOUDINARY_API_SECRET",
    CLOUD_API_KEY: "YOUR_CLOUDINARY_API_KEY"
}

export default CLOUDINARY_SECRETS;